--
-- PostgreSQL database dump
--

\restrict lm7aw5h4khIHyyoEakhzFcy8LyZdy6wjUBae7BzBnzG497bCm5fJdF32pd3vEMR

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-10-12 14:21:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 230 (class 1259 OID 16448)
-- Name: favorite_list_movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_list_movies (
    list_movie_id integer NOT NULL,
    list_id integer NOT NULL,
    movie_id integer NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    added_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.favorite_list_movies OWNER TO postgres;

--
-- TOC entry 4984 (class 0 OID 0)
-- Dependencies: 230
-- Name: COLUMN favorite_list_movies.sort_order; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_list_movies.sort_order IS 'Järjestys listassa';


--
-- TOC entry 229 (class 1259 OID 16447)
-- Name: favorite_list_movies_list_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorite_list_movies ALTER COLUMN list_movie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_list_movies_list_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16435)
-- Name: favorite_lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_lists (
    list_id integer NOT NULL,
    user_id integer NOT NULL,
    list_name character varying(255) NOT NULL,
    share_url character varying(255),
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.favorite_lists OWNER TO postgres;

--
-- TOC entry 4985 (class 0 OID 0)
-- Dependencies: 228
-- Name: COLUMN favorite_lists.list_name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_lists.list_name IS 'Suosikkilistan nimi, esim "Omat suosikit"';


--
-- TOC entry 4986 (class 0 OID 0)
-- Dependencies: 228
-- Name: COLUMN favorite_lists.share_url; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_lists.share_url IS 'Jaettava URI, null jos ei jaettu';


--
-- TOC entry 4987 (class 0 OID 0)
-- Dependencies: 228
-- Name: COLUMN favorite_lists.is_default; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_lists.is_default IS 'Onko käyttäjän oletuslista';


--
-- TOC entry 227 (class 1259 OID 16434)
-- Name: favorite_lists_list_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorite_lists ALTER COLUMN list_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_lists_list_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16406)
-- Name: group_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_members (
    member_id integer NOT NULL,
    group_id integer NOT NULL,
    user_id integer NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    joined_at timestamp without time zone,
    requested_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.group_members OWNER TO postgres;

--
-- TOC entry 4988 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN group_members.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_members.status IS 'pending, approved, rejected';


--
-- TOC entry 221 (class 1259 OID 16405)
-- Name: group_members_member_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_members ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_members_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16456)
-- Name: group_movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_movies (
    group_movie_id integer NOT NULL,
    group_id integer NOT NULL,
    movie_id integer NOT NULL,
    added_by_user_id integer NOT NULL,
    added_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.group_movies OWNER TO postgres;

--
-- TOC entry 4989 (class 0 OID 0)
-- Dependencies: 232
-- Name: COLUMN group_movies.added_by_user_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_movies.added_by_user_id IS 'Kuka lisäsi';


--
-- TOC entry 231 (class 1259 OID 16455)
-- Name: group_movies_group_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_movies ALTER COLUMN group_movie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_movies_group_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16463)
-- Name: group_showtimes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_showtimes (
    group_showtime_id integer NOT NULL,
    group_id integer NOT NULL,
    theater_name character varying(255) NOT NULL,
    movie_title character varying(255) NOT NULL,
    showtime timestamp without time zone NOT NULL,
    added_by_user_id integer NOT NULL,
    added_at timestamp without time zone DEFAULT now() NOT NULL,
    image_url character varying(255)
);


ALTER TABLE public.group_showtimes OWNER TO postgres;

--
-- TOC entry 4990 (class 0 OID 0)
-- Dependencies: 234
-- Name: COLUMN group_showtimes.theater_name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.theater_name IS 'Teatteri';


--
-- TOC entry 4991 (class 0 OID 0)
-- Dependencies: 234
-- Name: COLUMN group_showtimes.movie_title; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.movie_title IS 'Elokuvan nimi Finnkino API:sta';


--
-- TOC entry 4992 (class 0 OID 0)
-- Dependencies: 234
-- Name: COLUMN group_showtimes.showtime; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.showtime IS 'Esitysaika';


--
-- TOC entry 233 (class 1259 OID 16462)
-- Name: group_showtimes_group_showtime_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_showtimes ALTER COLUMN group_showtime_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_showtimes_group_showtime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16398)
-- Name: groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groups (
    group_id integer NOT NULL,
    group_name character varying(255) NOT NULL,
    owner_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.groups OWNER TO postgres;

--
-- TOC entry 4993 (class 0 OID 0)
-- Dependencies: 220
-- Name: COLUMN groups.group_name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.groups.group_name IS 'Ryhmän nimi';


--
-- TOC entry 4994 (class 0 OID 0)
-- Dependencies: 220
-- Name: COLUMN groups.owner_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.groups.owner_id IS 'Ryhmän luoja/omistaja';


--
-- TOC entry 219 (class 1259 OID 16397)
-- Name: groups_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.groups ALTER COLUMN group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16414)
-- Name: movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movies (
    movie_id integer NOT NULL,
    tmdb_id character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    poster_url character varying(500),
    release_year integer,
    genre character varying(255),
    tmdb_rating double precision,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.movies OWNER TO postgres;

--
-- TOC entry 4995 (class 0 OID 0)
-- Dependencies: 224
-- Name: COLUMN movies.tmdb_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.movies.tmdb_id IS 'The Movie Database ID';


--
-- TOC entry 223 (class 1259 OID 16413)
-- Name: movies_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movies ALTER COLUMN movie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16425)
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    review_id integer NOT NULL,
    user_id integer NOT NULL,
    movie_id integer NOT NULL,
    review_text text NOT NULL,
    rating integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- TOC entry 4996 (class 0 OID 0)
-- Dependencies: 226
-- Name: COLUMN reviews.rating; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.reviews.rating IS '1-5 tähteä';


--
-- TOC entry 225 (class 1259 OID 16424)
-- Name: reviews_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16386)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    theme character varying(50) DEFAULT 'default'::character varying
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 4997 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN users.email; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.users.email IS 'Käyttäjätunnus';


--
-- TOC entry 4998 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN users.password_hash; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.users.password_hash IS 'Min 8 merkkiä, iso kirjain, numero';


--
-- TOC entry 217 (class 1259 OID 16385)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4815 (class 2606 OID 16454)
-- Name: favorite_list_movies favorite_list_movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_list_movies
    ADD CONSTRAINT favorite_list_movies_pkey PRIMARY KEY (list_movie_id);


--
-- TOC entry 4809 (class 2606 OID 16444)
-- Name: favorite_lists favorite_lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_lists
    ADD CONSTRAINT favorite_lists_pkey PRIMARY KEY (list_id);


--
-- TOC entry 4811 (class 2606 OID 16446)
-- Name: favorite_lists favorite_lists_share_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_lists
    ADD CONSTRAINT favorite_lists_share_url_key UNIQUE (share_url);


--
-- TOC entry 4798 (class 2606 OID 16412)
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (member_id);


--
-- TOC entry 4818 (class 2606 OID 16461)
-- Name: group_movies group_movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_pkey PRIMARY KEY (group_movie_id);


--
-- TOC entry 4820 (class 2606 OID 16470)
-- Name: group_showtimes group_showtimes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_showtimes
    ADD CONSTRAINT group_showtimes_pkey PRIMARY KEY (group_showtime_id);


--
-- TOC entry 4795 (class 2606 OID 16404)
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (group_id);


--
-- TOC entry 4802 (class 2606 OID 16421)
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (movie_id);


--
-- TOC entry 4804 (class 2606 OID 16423)
-- Name: movies movies_tmdb_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_tmdb_id_key UNIQUE (tmdb_id);


--
-- TOC entry 4806 (class 2606 OID 16433)
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (review_id);


--
-- TOC entry 4800 (class 2606 OID 16552)
-- Name: group_members uq_group_members_group_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT uq_group_members_group_user UNIQUE (group_id, user_id);


--
-- TOC entry 4791 (class 2606 OID 16396)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4793 (class 2606 OID 16394)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4813 (class 1259 OID 16474)
-- Name: favorite_list_movies_list_id_movie_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX favorite_list_movies_list_id_movie_id_idx ON public.favorite_list_movies USING btree (list_id, movie_id);


--
-- TOC entry 4812 (class 1259 OID 16473)
-- Name: favorite_lists_user_id_is_default_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX favorite_lists_user_id_is_default_idx ON public.favorite_lists USING btree (user_id, is_default);


--
-- TOC entry 4796 (class 1259 OID 16471)
-- Name: group_members_group_id_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX group_members_group_id_user_id_idx ON public.group_members USING btree (group_id, user_id);


--
-- TOC entry 4816 (class 1259 OID 16475)
-- Name: group_movies_group_id_movie_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX group_movies_group_id_movie_id_idx ON public.group_movies USING btree (group_id, movie_id);


--
-- TOC entry 4807 (class 1259 OID 16472)
-- Name: reviews_user_id_movie_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX reviews_user_id_movie_id_idx ON public.reviews USING btree (user_id, movie_id);


--
-- TOC entry 4827 (class 2606 OID 16506)
-- Name: favorite_list_movies favorite_list_movies_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_list_movies
    ADD CONSTRAINT favorite_list_movies_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.favorite_lists(list_id);


--
-- TOC entry 4828 (class 2606 OID 16511)
-- Name: favorite_list_movies favorite_list_movies_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_list_movies
    ADD CONSTRAINT favorite_list_movies_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id);


--
-- TOC entry 4826 (class 2606 OID 16501)
-- Name: favorite_lists favorite_lists_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_lists
    ADD CONSTRAINT favorite_lists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4822 (class 2606 OID 16546)
-- Name: group_members group_members_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(group_id) ON DELETE CASCADE;


--
-- TOC entry 4823 (class 2606 OID 16486)
-- Name: group_members group_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4829 (class 2606 OID 16526)
-- Name: group_movies group_movies_added_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4830 (class 2606 OID 16516)
-- Name: group_movies group_movies_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(group_id);


--
-- TOC entry 4831 (class 2606 OID 16521)
-- Name: group_movies group_movies_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id);


--
-- TOC entry 4832 (class 2606 OID 16541)
-- Name: group_showtimes group_showtimes_added_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_showtimes
    ADD CONSTRAINT group_showtimes_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4833 (class 2606 OID 16531)
-- Name: group_showtimes group_showtimes_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_showtimes
    ADD CONSTRAINT group_showtimes_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(group_id);


--
-- TOC entry 4821 (class 2606 OID 16476)
-- Name: groups groups_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(user_id);


--
-- TOC entry 4824 (class 2606 OID 16496)
-- Name: reviews reviews_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id);


--
-- TOC entry 4825 (class 2606 OID 16491)
-- Name: reviews reviews_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


-- Completed on 2025-10-12 14:21:39

--
-- PostgreSQL database dump complete
--

\unrestrict lm7aw5h4khIHyyoEakhzFcy8LyZdy6wjUBae7BzBnzG497bCm5fJdF32pd3vEMR

